on: [push]

jobs:
  s3_job:
    runs-on: ubuntu-latest
    name: S3 test job
    steps:
    - name: copy repo
      uses: actions/checkout@master
    - name: Run s3 copy
      uses: rjmendus/github-action-s3-upload@master
      env:
        TO_UPLOAD: ./test.py
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
